# Generated by Django 4.2.11 on 2024-04-16 17:22

import django.db.models.deletion
from django.db import migrations, models

import data_products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("assayName", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.CharField(max_length=32)),
                ("hbmid", models.CharField(max_length=16)),
                (
                    "annotation_metadata",
                    models.JSONField(default=data_products.models.annotation_default),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tissue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tissuetype", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="DataProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dataProductId", models.CharField(max_length=32)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                ("datasets", models.ManyToManyField(to="data_products.dataset")),
                (
                    "tissue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data_products.tissue"
                    ),
                ),
            ],
        ),
    ]
