# Generated by Django 4.2.11 on 2024-04-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_products", "0003_dataproduct_umap_plot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataproduct",
            name="umap_plot",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
