# Generated by Django 4.2.11 on 2024-04-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_products", "0004_alter_dataproduct_umap_plot"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataproduct",
            name="download",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
