# Generated by Django 4.2.11 on 2024-06-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_products", "0005_dataproduct_download"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataproduct",
            name="shinyApp",
            field=models.URLField(blank=True, null=True),
        ),
    ]
