version: '3'

services:
  db:
    image: "postgres:16"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
  web:
    image: "hubmap/data-products-ui-dev:latest"
    command: /code/wait-for-it.sh --timeout=0 db:5432 -- /opt/venv/bin/python /code/hubmap/manage.py runserver 0.0.0.0:8000
    volumes:
      - ../..:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
