version: '3'

services:
  db:
    image: "postgres:16"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      -  /data/postgres:/var/lib/postgresql/data
  uwsgi:
    image: "hubmap/data-products-ui-prod:latest"
    ports:
      - "5000:5000"
    expose:
      - 5000
    volumes:
      - /opt/secret:/opt/secret
      - /opt/data:/opt/data
      - /pipeline_outputs:/opt/pipeline_outputs
      - /media:/media