# Generated by Django 4.2.11 on 2024-04-23 02:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("data_products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataproduct",
            name="id",
        ),
        migrations.AlterField(
            model_name="dataproduct",
            name="dataProductId",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
