# Generated by Django 4.2.11 on 2024-04-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_products", "0002_remove_dataproduct_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataproduct",
            name="umap_plot",
            field=models.ImageField(default="images/leiden_cluster_combined", upload_to=""),
        ),
    ]
